<a href="https://colab.research.google.com/github/Ahadri94/DS-Unit-1-Sprint-2-Statistics/blob/master/DS28_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [ ]:
# YOUR WORK HERE

import numpy as np 
from scipy import stats
import pandas as pd 

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-07-16 06:30:03--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.06s   

2020-07-16 06:30:04 (316 KB/s) - ‘student.zip’ saved [20478/20478]



In [ ]:
!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [ ]:
df = pd.read_csv('student-mat.csv',sep=';')

print(df.shape)
df.head(10)

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10
5     GP   M   16       U     LE3       T  ...     2       5       10  15  15  15
6     GP   M   16       U     LE3       T  ...     1       3        0  12  12  11
7     GP   F   17       U     GT3       A  ...     1       1        6   6   5   6
8     GP   M   15       U     LE3       A  ...     1       1        0  16  18  19
9     GP   M   15       U     GT3       T  ...     1       5        0  14  15  15

[10 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [ ]:
df.describe(exclude='number')

school  sex address famsize  ... nursery higher internet romantic
count     395  395     395     395  ...     395    395      395      395
unique      2    2       2       2  ...       2      2        2        2
top        GP    F       U     GT3  ...     yes    yes      yes       no
freq      349  208     307     281  ...     314    375      329      263

[4 rows x 17 columns]

In [ ]:
#Two pairs of variables that are dependent 

In [ ]:
# YOUR WORK HERE

df1 = df[['sex','studytime']]

df1.head()

sex  studytime
0   F          2
1   F          2
2   F          2
3   F          3
4   F          2

In [ ]:
contingency_dep = pd.crosstab(df['sex'],df['studytime'], margins=True)
contingency_dep

studytime    1    2   3   4  All
sex                             
F           27  113  51  17  208
M           78   85  14  10  187
All        105  198  65  27  395

In [ ]:
df2 = df[['sex','romantic']]

df2.head()

sex romantic
0   F       no
1   F       no
2   F       no
3   F      yes
4   F       no

In [ ]:
contingency_ind = pd.crosstab(df['sex'],df['romantic'], margins=True)
contingency_ind

romantic   no  yes  All
sex                    
F         129   79  208
M         134   53  187
All       263  132  395

In [ ]:
observed = pd.crosstab(df['sex'],['romantic'])
observed

col_0  romantic
sex            
F           208
M           187

In [ ]:
observed.values

array([[208],
       [187]])

In [ ]:
# The two pairs are related since the data makes sense. 

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [ ]:
# YOUR WORK HER
males_no_health = 208* 47/395
males_no_health

24.749367088607595

In [ ]:
row_totals = df['romantic'].value_counts().sort_index().values
row_totals

array([263, 132])

In [ ]:
col_totals = df['sex'].value_counts().sort_index().values
col_totals

array([208, 187])

In [ ]:
sample_size = df.shape[0]

sample_size

395

In [ ]:
expected = np.array([[0.0,0,0],
                     [0.0,0.0]])

for row_position, col in enumerate(col_totals):
  for column_position, row in enumerate(row_totals):
    expected_value = (row*col) / sample_size
    expected[row_position][column_position] = expected_value

expected

array([list([138.49113924050633, 69.50886075949367, 0]),
       list([124.50886075949367, 62.49113924050633])], dtype=object)

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)